# Generated by Django 4.1.7 on 2023-02-26 11:37
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                (
                    'id', models.BigAutoField(
                        auto_created=True,
                        primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                (
                    'first_name', models.CharField(
                        max_length=255, null=True, verbose_name='First Name',
                    ),
                ),
                (
                    'last_name', models.CharField(
                        blank=True,
                        max_length=255, null=True, verbose_name='Last Name',
                    ),
                ),
                (
                    'sex', models.CharField(
                        blank=True, choices=[
                            ('M', 'Male'), ('F', 'Female'), (
                                'O', 'Other',
                            ), ('N', 'Rather not say'),
                        ], max_length=1, null=True, verbose_name='Sex',
                    ),
                ),
                (
                    'dob', models.DateField(
                        blank=True,
                        null=True, verbose_name='Date of birth',
                    ),
                ),
            ],
        ),
    ]
