# Generated by Django 4.1.7 on 2023-02-26 16:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('upin', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(blank=True, max_length=255, null=True)),
                ('longitude', models.CharField(
                    blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('pin_code', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pathologist',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(
                    max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True,
                 max_length=255, null=True, verbose_name='Last Name')),
                ('phone_number', models.CharField(max_length=15)),
                ('email_address', models.EmailField(blank=True,
                 max_length=255, null=True, verbose_name='Email Address')),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                 related_name='pathologist_laboratory', to='core.laboratory')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(
                    max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True,
                 max_length=255, null=True, verbose_name='Last Name')),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), (
                    'O', 'Other'), ('N', 'Rather not say')], max_length=1, null=True, verbose_name='Sex')),
                ('dob', models.DateField(blank=True,
                 null=True, verbose_name='Date of birth')),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('date_collected', models.DateTimeField(
                    blank=True, null=True, verbose_name='Date of collection')),
                ('diagnosis_code', models.CharField(blank=True,
                 max_length=8, null=True, verbose_name='Diagnosis Code')),
                ('type', models.CharField(blank=True, choices=[
                 ('B', 'biopsy'), ('SR', 'surgical resection'), ('O', 'Other')], max_length=50, null=True, verbose_name='Type')),
                ('origin', models.CharField(blank=True, choices=[('B', 'blood'), ('T', 'tissue'), ('U', 'urine'), (
                    'S', 'stool'), ('F', 'fluid'), ('O', 'Other')], max_length=50, null=True, verbose_name='Site of Origin')),
                ('symptoms', models.CharField(blank=True, max_length=800)),
                ('comments', models.CharField(blank=True, max_length=800)),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                 related_name='sample_laboratory', to='core.laboratory')),
                ('pathologists', models.ManyToManyField(
                    related_name='sample_pathologists', to='core.pathologist')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                 related_name='sample_patient', to='core.patient')),
            ],
        ),
        migrations.AddField(
            model_name='pathologist',
            name='patients',
            field=models.ManyToManyField(
                related_name='pathologist_patients', to='core.patient'),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='address',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='core.location'),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='admin_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                    related_name='laboratory_admin', to='core.pathologist'),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='pathologists',
            field=models.ManyToManyField(
                related_name='laboratory_pathologists', to='core.pathologist'),
        ),
    ]
