# Generated by Django 4.1.7 on 2023-02-26 14:02
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(default='9393938457', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='First Name'),
        ),
    ]
