# Generated by Django 4.1.7 on 2023-02-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_laboratory_upin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratory',
            name='pathologists',
            field=models.ManyToManyField(
                blank=True, null=True, related_name='laboratory_pathologists', to='core.pathologist'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='upin',
            field=models.CharField(
                default='<function uuid4 at 0x7fe97ef8e830>', max_length=255, unique=True),
        ),
    ]
