# Generated by Django 4.1.7 on 2023-02-26 14:03
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_patient_phone_number_alter_patient_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='phone_number',
        ),
    ]
