# Generated by Django 4.1.7 on 2023-02-26 14:04
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_patient_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(default='9393938345', max_length=15),
        ),
    ]
