# Generated by Django 4.1.7 on 2023-02-26 14:29
from __future__ import annotations

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_patient_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('date_collected', models.DateTimeField(
                    blank=True, null=True, verbose_name='Date of collection')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                 related_name='patient', to='core.patient')),
            ],
        ),
    ]
