# Generated by Django 4.1.7 on 2023-02-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_laboratory_pathologists_alter_laboratory_upin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratory',
            name='upin',
            field=models.CharField(default='<function uuid4 at 0x7f102c55e830>', max_length=255, unique=True),
        ),
    ]
