# Generated by Django 4.1.7 on 2023-02-26 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_customuser_options_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
