# Generated by Django 4.1.7 on 2023-02-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratory',
            name='pathologists',
            field=models.ManyToManyField(blank=True, related_name='laboratory_pathologists', to='core.pathologist'),
        ),
    ]
